# pyproject.toml
[tool.black]
line-length = 120
target-version = ["py310"]
include = '\.pyi$|\.py$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | \.vscode
  | _build
  | build
  | dist
  | venv
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["app", "tests"] # Adicione seus pacotes de código para que isort saiba que são internos
skip_glob = ["venv/*"] # Ignorar a pasta venv